### ISSUE TITLE
[Request] Would it be possible to calculate Frequency Domain values

### ISSUE THREAD

**Issue by vnl** [Przemekeke/flutter_hrv#1]
Frequency Domain Analysis technique that shows how much of a signal lies within one or more frequency bands (ranges). 

Common Frequency Domain HRV metrics include:

High-Frequency power (HF): frequency activity in the 0.15 - 0.40Hz range
Low-Frequency power (LF): frequency activity in the 0.04 - 0.15Hz range
LF/HF Ratio: A ratio of Low Frequency to High Frequency. 

Sorry just noticed the ToDos :)

**Comment by Przemekeke** [comment]
Hi, good point. It is definetely a valuable data. I've updated my code on github and it works to some extent. You can call `calcFrequencyDomain` and you will get HF, LF and LF/HF. It works the best with the recording of time  > 1 min  and < 5 minutes. I think still that there is some room for improvement because I haven't used interpolation to have a continous RRs signal

Also feel free to add some code by yourself since it is an open source
